package com.example.winplusmobile.Entities;


import java.time.LocalDateTime;


public class Personal {
    public String codigo;
    public String nombre;
    public String apellido1;
    public String apellido2;
    public String tarjeta;
    public String telefono;
    public String centro;
    public String departamento;
    public String seccion;
    public String categoria;
    public String dni;
    public String calendario;
    public byte tipoControl;
    public byte salidaAutomatica;
    public String fechaIngreso;
    public LocalDateTime fechaBaja;
    public String ultimoFichaje;
    public byte ultimaFuncion;
    public byte ultimaCausa;
    public String foto;
    public int saldo1;
    public int saldo2;
    public int saldo3;
    public int saldo4;
    public String observaciones;
    public String sexo;
    public String password;
    public short cgastos1;
    public short cgastos2;
    public short cgastos3;
    public float pcgastos1;
    public float pcgastos2;
    public float pcgastos3;
    public String perfil;
    public LocalDateTime ultimoAcceso;
    public String empresa;
    public short permisos;
    public byte conprod;
    public String pcoste;
    public String resCen;
    public String resDep;
    public String adjDep;
    public String secDep;
    public byte facceso;
    public String colectivo;
    public String empresaExterna;
    public String email;
    public String ultimaFicha;
    public String pin;
    public byte bloqueado;
    public String direccion;
    public String localidad;
    public String provincia;
    public String cpostal;
    public String estadoCivil;
    public LocalDateTime fnacimiento;
    public String pais;
    public String ultimoLocal;
    public boolean vantipassback;
    public byte notRescen;
    public byte notResDep;
    public byte notAdjDep;
    public byte notSecDep;
    public int saldoInicial;
    public byte wpmobile;
    public String tarjetaCi;
    public String salto_ExtUserId;
    public byte estado;
    public String cdesbloqueo;
    public LocalDateTime fdesbloqueo;
    public short nreintentos;
    public String ultimoCentro;
}
